#!/bin/bash
echo "Enter 'd' to update to latest Dev version, 'r' to latest Public Release version, or 'c' to enter a custom url to a PhotonVision jar file."
read str1

#Setting Download Url
if [ "$str1" == "d" ]; then
    METHOD="api"
    URL="https://api.github.com/repos/photonvision/photonvision/releases/tags/Dev"
elif [ "$str1" == "r" ]; then
    METHOD="api"
    URL="https://api.github.com/repos/photonvision/photonvision/releases/latest"
elif [ "$str1" == "c" ]; then
    METHOD="link"
    echo "Enter the url to the PhotonVision jar file:"
    read URL
else
    echo "invalid input"
    exit 1
fi

#Updating
sudo systemctl stop photonvision

if [ "$METHOD" == "api" ]; then
    curl -k -s $URL \
    | grep "browser_download_url.*jar" \
    | cut -d : -f 2,3 \
    | tr -d \" \
    | wget -qi - --show-progress -O /opt/photonvision/photonvision.jar
elif [ "$METHOD" == "link" ]; then
    wget -qi $URL --show-progress -O /opt/photonvision/photonvision.jar
fi

sudo systemctl start photonvision