#!/bin/bash
echo "Enter 'd' to update to latest Dev version, 'r' to latest Public Release version"
read str1

#setting download url
if [ "$str1" == "d" ]; then
    URL="https://api.github.com/repos/photonvision/photonvision/releases/tags/Dev"
elif [ "$str1" == "r" ]; then
    URL="https://api.github.com/repos/photonvision/photonvision/releases/latest"
else
    echo "invalid input"
    exit 1    
fi

#installing any necessary dependencies
if command -V curl >/dev/null 2>&1 ; then
    echo "curl found"
else
    sudo apt-get -y install curl
fi
if command -V wget >/dev/null 2>&1 ; then
    echo "wget found"
else
    sudo apt-get -y install wget
fi

#updating
sudo systemctl stop photonvision

curl -k -s $URL \
| grep "browser_download_url.*jar" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi - --show-progress -O /opt/photonvision/photonvision.jar

sudo systemctl start photonvision